;		WuWa Mobile Config for Version 3.6
; ============================================================
; 			ChangeLog:
[Android_VeryHigh DeviceProfile]
; To get both Frame Gen and Vulkan Toggle, change "Android_VeryHigh" to "Android_Adreno840"
; Also change the dp.Override in Engine.ini to dp.Override="Android_Adreno840"
DeviceScore=69696
CVars=t.MaxFPS=120
CVars=r.Mobile.HighQualityMaterial=1
CVars=r.Android.DisableVulkanSupport=0
CVars=r.Android.VulkanSetting=1
CVars=r.Mobile.EnergySavingFrameInterpolation=0
CVars=sg.ViewDistanceQuality=4
CVars=sg.AntiAliasingQuality=4
CVars=sg.ShadowQuality=3
CVars=sg.PostProcessQuality=6
CVars=sg.TextureQuality=6
CVars=sg.EffectsQuality=2
CVars=sg.FoliageQuality=3
CVars=sg.ShadingQuality=3
CVars=wp.Runtime.LoadingRangeScale=0.85
CVars=wp.Runtime.PlannedLoadingRangeScale=1.05